# Project configuration
project.name=Web_Lab3
project.version=1.0

# Directory paths
src.dir=src/main/java
resources.dir=src/main/resources
webapp.dir=src/main/webapp
build.dir=build
build.classes.dir=${build.dir}/classes
build.jar.dir=${build.dir}/jar

# Test directory paths
src.test.dir=src/test/java
build.test.classes.dir=${build.dir}/test-classes
build.test.reports.dir=${build.dir}/test-reports

# Documentation output
build.javadoc.dir=${build.dir}/docs

# Main project dependencies
lib.dir=target/Web_Lab3/WEB-INF/lib

# Test dependencies
test.lib.dir=lib

# Path to local Maven repository
m2.repo=${user.home}/.m2/repository

# Manifest configuration
main.class=web.MainApp

# Remote server (Helios) parameters scp
scp.server=se.ifmo.ru
scp.port=2222
scp.username=${env.HELIOS_USER}
scp.password=${env.HELIOS_PASS}
scp.dest.dir=~

# Target 12 Environment Config
diff.critical.classes=AreaCalculator.java,InputBean.java

# Target 14 Alternative Environments Config
env.java.home=/Users/macbook/Library/Java/JavaVirtualMachines/openjdk-23.0.1/Contents/Home
env.jvm.args=-Xms64m -Xmx256m